spring:
  application:
    name: iLikeMovie

# ???? ??, ??? ???, ???? ??
# ??(:)??? ???? ?? ??

  datasource:
    driver-calss-name: org.mariadb.jdbc.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/moviecafe
    username: root
    password: green502

mybatis:
  mapper-locations: mappers/**/*.xml
# ??? ?? ?? ????? ??

springdoc:
  swagger-ui:
    path: /swagger
# ??? ??? ????? ??